name: mapget
version: '1.2.0'
main: space.kararasenok.mapget.Mapget
api-version: '1.21'

permissions:
  mapget.reload:
    description: Allows access to the /map reload command
    default: op
  mapget.get:
    description: Allows access to the /map get command
    default: true
  mapget.temp:
    description: Allows to create temporary maps even if allowTemporaryMaps setting is false
    default: op
  mapget.*:
    description: :P
    children:
      mapget.reload: true
      mapget.get: true
      mapget.temp: true