name: mapget
description: $description
version: '${version}'
authors: [ kararasenok-gd ]

main: space.kararasenok.mapget.Mapget
api-version: '26.1'

permissions:
  mapget.reload:
    description: Allows access to the /map reload command
    default: op

  mapget.get:
    description: Allows access to the /map get command
    default: true

  mapget.temp:
    description: Allows to create temporary maps even if allowTemporaryMaps setting is false
    default: op

  mapget.update:
    description: Allows to use /map update command
    default: op

  mapget.bypass:
    description: Allows to bypass all mapget restrictions
    default: false
    children:
      mapget.bypass.ownership: true
      mapget.bypass.size: true

  mapget.bypass.ownership:
    description: Allows to bypass ownership checks
    default: false

  mapget.bypass.size:
    description: Allows to bypass maxGridSize limit
    default: false

  mapget.*:
    description: :P
    children:
      mapget.reload: true
      mapget.get: true
      mapget.temp: true
      mapget.update: true
      mapget.bypass: true